services:
  esdb:
    image: docker.io/thenativeweb/eventsourcingdb:1.0.3
    command: "run --api-token secret --data-directory-temporary --with-ui --http-enabled=true --https-enabled=false"
    ports:
      - "3000:3000"
